import { SkinCategory, SkinItem, PlayerSkinsConfig } from '../types';

export const ALL_SKINS: SkinItem[] = [
  // ================= THEMES (Mavzular) =================
  {
    id: 'theme_cyber',
    name: 'Cyber Space',
    nameUz: 'Kiber Kosmos',
    category: 'theme',
    price: 0,
    description: "Boshlang'ich klassik kiber koinot foni va zamonaviy ko'k-binafsha tuslar.",
    icon: '🌌',
    previewGradient: 'from-slate-950 via-slate-900 to-indigo-950',
    tag: 'Asosiy',
    themeStyles: {
      appBackground: 'bg-slate-950',
      boardBackground: 'bg-slate-900/95',
      boardBorder: 'border-slate-800',
      hudBackground: 'bg-slate-850/90',
      hudBorder: 'border-slate-700/80',
      accentColor: 'text-amber-400',
      accentGlow: 'shadow-amber-500/20',
    },
  },
  {
    id: 'theme_volcano',
    name: 'Lava Volcano',
    nameUz: 'Olovli Vulqon',
    category: 'theme',
    price: 300,
    description: "Yonayotgan magma, qizg'in olov va qizil-to'q sariq ajoyib energetik fon.",
    icon: '🌋',
    previewGradient: 'from-stone-950 via-red-950 to-orange-950',
    tag: 'Mashhur',
    themeStyles: {
      appBackground: 'bg-stone-950',
      boardBackground: 'bg-stone-900/95',
      boardBorder: 'border-orange-900/80',
      hudBackground: 'bg-stone-900/90',
      hudBorder: 'border-orange-800/60',
      accentColor: 'text-orange-400',
      accentGlow: 'shadow-orange-500/30',
    },
  },
  {
    id: 'theme_emerald',
    name: 'Emerald Matrix',
    nameUz: "Zumrad O'rmon",
    category: 'theme',
    price: 500,
    description: "Zumrad yashil kiber kodlar va tinchlantiruvchi yashil tabiat energiyasi.",
    icon: '🌲',
    previewGradient: 'from-zinc-950 via-emerald-950 to-teal-950',
    tag: 'Eko',
    themeStyles: {
      appBackground: 'bg-zinc-950',
      boardBackground: 'bg-zinc-900/95',
      boardBorder: 'border-emerald-900/80',
      hudBackground: 'bg-zinc-900/90',
      hudBorder: 'border-emerald-800/60',
      accentColor: 'text-emerald-400',
      accentGlow: 'shadow-emerald-500/30',
    },
  },
  {
    id: 'theme_neon',
    name: 'Cyberpunk Neon',
    nameUz: 'Kiberpunk Neon',
    category: 'theme',
    price: 800,
    description: "Yorqin neon pushti, binafsha va kiber shahar tungi manzarasi.",
    icon: '🔮',
    previewGradient: 'from-purple-950 via-fuchsia-950 to-pink-950',
    tag: 'Yorqin',
    themeStyles: {
      appBackground: 'bg-slate-950',
      boardBackground: 'bg-purple-950/90',
      boardBorder: 'border-fuchsia-700/60',
      hudBackground: 'bg-purple-900/80',
      hudBorder: 'border-fuchsia-600/50',
      accentColor: 'text-fuchsia-400',
      accentGlow: 'shadow-fuchsia-500/40',
    },
  },
  {
    id: 'theme_gold',
    name: 'Royal Gold',
    nameUz: 'Qirollik Oltini',
    category: 'theme',
    price: 1200,
    description: "Haqiqiy chempionlar uchun tilla rang, oltin ramkalar va hashamatli dizayn.",
    icon: '👑',
    previewGradient: 'from-amber-950 via-yellow-950 to-stone-950',
    tag: 'VIP',
    themeStyles: {
      appBackground: 'bg-amber-950/95',
      boardBackground: 'bg-stone-900/95',
      boardBorder: 'border-amber-500/60',
      hudBackground: 'bg-stone-900/90',
      hudBorder: 'border-amber-600/60',
      accentColor: 'text-amber-300',
      accentGlow: 'shadow-amber-400/40',
    },
  },
  {
    id: 'theme_frost',
    name: 'Arctic Frost',
    nameUz: 'Muzlik Dunyosi',
    category: 'theme',
    price: 1600,
    description: "Muzdek tiniq ko'k va oq kristall muhit, sovuqqon hisob-kitoblar uchun.",
    icon: '❄️',
    previewGradient: 'from-sky-950 via-cyan-950 to-blue-950',
    tag: 'Kristall',
    themeStyles: {
      appBackground: 'bg-slate-950',
      boardBackground: 'bg-sky-950/90',
      boardBorder: 'border-cyan-700/60',
      hudBackground: 'bg-sky-900/80',
      hudBorder: 'border-cyan-600/60',
      accentColor: 'text-cyan-300',
      accentGlow: 'shadow-cyan-400/40',
    },
  },
  {
    id: 'theme_galaxy',
    name: 'Cosmic Void',
    nameUz: 'Galaktik Tuynuk',
    category: 'theme',
    price: 2500,
    description: "Koinotning cheksiz yulduzlari, qora tuynuk nurlari va afsonaviy aura.",
    icon: '🪐',
    previewGradient: 'from-violet-950 via-indigo-950 to-slate-950',
    tag: 'Afsonaviy',
    themeStyles: {
      appBackground: 'bg-black',
      boardBackground: 'bg-indigo-950/90',
      boardBorder: 'border-violet-600/70',
      hudBackground: 'bg-violet-950/80',
      hudBorder: 'border-violet-500/60',
      accentColor: 'text-violet-300',
      accentGlow: 'shadow-violet-500/50',
    },
  },

  // ================= AVATARS (Qahramonlar & Avatarlar) =================
  {
    id: 'avatar_bot',
    name: 'Math Bot 3000',
    nameUz: 'Math Bot 3000',
    category: 'avatar',
    price: 0,
    description: "Boshlang'ich kiber robot hisobchi yordamchisi.",
    icon: '🤖',
    previewGradient: 'from-slate-800 to-indigo-900',
    tag: 'Asosiy',
    avatarData: {
      emoji: '🤖',
      badgeText: 'Kiber Bot',
      colorClass: 'text-indigo-400',
      borderClass: 'border-indigo-500/50',
    },
  },
  {
    id: 'avatar_wizard',
    name: 'Math Wizard',
    nameUz: 'Hisob Sehrgari',
    category: 'avatar',
    price: 250,
    description: "Raqamlarni ko'z ochib yumguncha sehrlab to'g'ri topuvchi donishmand.",
    icon: '🧙‍♂️',
    previewGradient: 'from-purple-900 to-indigo-900',
    tag: 'Sehrli',
    avatarData: {
      emoji: '🧙‍♂️',
      badgeText: 'Sehrgar',
      colorClass: 'text-purple-400',
      borderClass: 'border-purple-500/60',
    },
  },
  {
    id: 'avatar_cat',
    name: 'Smart Neko',
    nameUz: 'Aqliy Mushukcha',
    category: 'avatar',
    price: 400,
    description: "Tezkor va epchil mushukcha, xatolarni ko'rmasdan qoldirmaydi!",
    icon: '🐱',
    previewGradient: 'from-amber-800 to-orange-900',
    tag: 'Quvnoq',
    avatarData: {
      emoji: '🐱',
      badgeText: 'Aqliy Mushuk',
      colorClass: 'text-amber-400',
      borderClass: 'border-amber-500/60',
    },
  },
  {
    id: 'avatar_astro',
    name: 'Astro Explorer',
    nameUz: 'Koinot Sayyohi',
    category: 'avatar',
    price: 700,
    description: "Yulduzlararo fazoviy sarguzashtchi va yangi bilimlarni kashf etuvchi.",
    icon: '🚀',
    previewGradient: 'from-blue-900 to-cyan-900',
    tag: 'Sayyoh',
    avatarData: {
      emoji: '🚀',
      badgeText: 'Fazogir',
      colorClass: 'text-cyan-400',
      borderClass: 'border-cyan-500/60',
    },
  },
  {
    id: 'avatar_dragon',
    name: 'Fire Dragon',
    nameUz: 'Olovli Ajdaho',
    category: 'avatar',
    price: 1100,
    description: "Misollarni olovdek tez yechuvchi va yuqori comboga ega kuchli ajdaho.",
    icon: '🐲',
    previewGradient: 'from-rose-900 to-red-950',
    tag: 'Ajdaho',
    avatarData: {
      emoji: '🐲',
      badgeText: 'Olov Ajdaho',
      colorClass: 'text-rose-400',
      borderClass: 'border-rose-500/60',
    },
  },
  {
    id: 'avatar_king',
    name: 'Math King',
    nameUz: 'Matematika Qiroli',
    category: 'avatar',
    price: 1800,
    description: "Al-Xorazmiyning eng iqtidorli shogirdi va tengsiz hisob sultoni.",
    icon: '👑',
    previewGradient: 'from-yellow-800 to-amber-950',
    tag: 'Qirollik',
    avatarData: {
      emoji: '👑',
      badgeText: 'Hisob Qiroli',
      colorClass: 'text-yellow-400',
      borderClass: 'border-yellow-500/60',
    },
  },
  {
    id: 'avatar_cyborg',
    name: 'Cyber Genius',
    nameUz: 'Kvant Kiborg',
    category: 'avatar',
    price: 2500,
    description: "Superkompyuter miyasiga ega mutlaq kiber intellekt.",
    icon: '⚡',
    previewGradient: 'from-teal-800 to-emerald-950',
    tag: 'Afsonaviy',
    avatarData: {
      emoji: '⚡',
      badgeText: 'Kvant Kiborg',
      colorClass: 'text-emerald-400',
      borderClass: 'border-emerald-500/70',
    },
  },

  // ================= CARD FRAMES & AURAS (Ramkalar & Aura) =================
  {
    id: 'frame_classic',
    name: 'Classic Slate',
    nameUz: 'Klassik Neon',
    category: 'cardFrame',
    price: 0,
    description: "Standart qulay va ko'zni charchatmaydigan kiber ramka.",
    icon: '🟦',
    previewGradient: 'from-slate-800 to-slate-900',
    tag: 'Asosiy',
    cardStyles: {
      borderClass: 'border-2 border-slate-700/80',
      glowShadowClass: 'shadow-xl shadow-slate-950/50',
      headerBadgeClass: 'bg-slate-800/90 text-slate-300 border-slate-700',
      innerCardBg: 'bg-slate-950/70',
      accentText: 'text-amber-400',
    },
  },
  {
    id: 'frame_fire',
    name: 'Inferno Fire Aura',
    nameUz: 'Olovli Aura',
    category: 'cardFrame',
    price: 350,
    description: "Misollar kartasi atrofida alanga va kuchli olov aurasini beradi.",
    icon: '🔥',
    previewGradient: 'from-red-900 to-orange-950',
    tag: 'Olovli',
    cardStyles: {
      borderClass: 'border-2 border-orange-500',
      glowShadowClass: 'shadow-2xl shadow-orange-500/40 ring-2 ring-orange-500/30',
      headerBadgeClass: 'bg-red-950/90 text-orange-300 border-orange-700',
      innerCardBg: 'bg-stone-950/80',
      accentText: 'text-orange-400',
    },
  },
  {
    id: 'frame_lightning',
    name: 'Lightning Plasma',
    nameUz: 'Chaqmoq Plazmasi',
    category: 'cardFrame',
    price: 600,
    description: "Yuqori kuchlanishli ko'k chaqmoq nurlari va elektr porlashi.",
    icon: '⚡',
    previewGradient: 'from-blue-900 to-cyan-950',
    tag: 'Elektr',
    cardStyles: {
      borderClass: 'border-2 border-cyan-400',
      glowShadowClass: 'shadow-2xl shadow-cyan-500/40 ring-2 ring-cyan-400/40 animate-pulse-subtle',
      headerBadgeClass: 'bg-cyan-950/90 text-cyan-200 border-cyan-600',
      innerCardBg: 'bg-slate-950/80',
      accentText: 'text-cyan-300',
    },
  },
  {
    id: 'frame_gold',
    name: 'Golden Radiance',
    nameUz: 'Oltin Spark',
    category: 'cardFrame',
    price: 1000,
    description: "Tilla bilan jilolangan yaltiroq chegara va boy ko'rinish.",
    icon: '✨',
    previewGradient: 'from-yellow-900 to-amber-950',
    tag: 'Oltin',
    cardStyles: {
      borderClass: 'border-2 border-amber-400',
      glowShadowClass: 'shadow-2xl shadow-amber-400/40 ring-2 ring-amber-300/30',
      headerBadgeClass: 'bg-amber-950/90 text-amber-200 border-amber-500',
      innerCardBg: 'bg-neutral-950/80',
      accentText: 'text-amber-300',
    },
  },
  {
    id: 'frame_rainbow',
    name: 'Rainbow Prism',
    nameUz: 'Kamalak Spektri',
    category: 'cardFrame',
    price: 1500,
    description: "Barcha ranglar bilan tovlanuvchi sehrli kamalak aurası.",
    icon: '🌈',
    previewGradient: 'from-pink-900 via-purple-900 to-indigo-900',
    tag: 'Spektr',
    cardStyles: {
      borderClass: 'border-2 border-pink-500',
      glowShadowClass: 'shadow-2xl shadow-pink-500/30 ring-2 ring-purple-500/40',
      headerBadgeClass: 'bg-purple-950/90 text-pink-200 border-pink-500',
      innerCardBg: 'bg-slate-950/80',
      accentText: 'text-pink-300',
    },
  },
  {
    id: 'frame_crystal',
    name: 'Diamond Crystal',
    nameUz: 'Olmos Kristall',
    category: 'cardFrame',
    price: 2200,
    description: "Tiniq olmos yorqinligi va kristall porlash effekti.",
    icon: '💎',
    previewGradient: 'from-teal-900 to-emerald-950',
    tag: 'Olmos',
    cardStyles: {
      borderClass: 'border-2 border-emerald-400',
      glowShadowClass: 'shadow-2xl shadow-emerald-400/40 ring-2 ring-teal-300/40',
      headerBadgeClass: 'bg-emerald-950/90 text-emerald-200 border-emerald-400',
      innerCardBg: 'bg-zinc-950/85',
      accentText: 'text-emerald-300',
    },
  },

  // ================= BUTTON STYLES (Tugmalar Uslubi) =================
  {
    id: 'btn_modern',
    name: 'Modern Sleek',
    nameUz: 'Zamonaviy Silliq',
    category: 'buttonStyle',
    price: 0,
    description: "Silliq qora-ko'k fon, qulay va aniq bosilish effekti.",
    icon: '🔘',
    previewGradient: 'from-slate-800 to-slate-900',
    tag: 'Asosiy',
    buttonStyles: {
      baseClass: 'bg-slate-800/90 hover:bg-slate-700/90 border-2 border-slate-700/80 text-white active:scale-95',
      selectedClass: 'bg-amber-500 text-slate-950 border-amber-400 font-black shadow-lg shadow-amber-500/30',
      correctClass: 'bg-emerald-500 text-slate-950 border-emerald-400 font-black shadow-lg shadow-emerald-500/40',
      wrongClass: 'bg-rose-500 text-white border-rose-400 font-black shadow-lg shadow-rose-500/40',
      indicatorClass: 'bg-slate-700/80 text-slate-300',
    },
  },
  {
    id: 'btn_retro',
    name: 'Retro Arcade',
    nameUz: 'Retro Arkada',
    category: 'buttonStyle',
    price: 400,
    description: "80-yillar o'yin avtomatlari uslubidagi qalin qavariq tugmalar.",
    icon: '🎮',
    previewGradient: 'from-violet-900 to-purple-950',
    tag: 'Retro',
    buttonStyles: {
      baseClass: 'bg-indigo-900 hover:bg-indigo-800 border-b-4 border-r-2 border-indigo-600 text-yellow-300 font-mono active:border-b-0 active:translate-y-1',
      selectedClass: 'bg-yellow-400 text-indigo-950 border-b-4 border-yellow-600 font-black',
      correctClass: 'bg-green-400 text-slate-950 border-b-4 border-green-700 font-black',
      wrongClass: 'bg-red-500 text-white border-b-4 border-red-800 font-black',
      indicatorClass: 'bg-indigo-950 text-yellow-400 font-mono',
    },
  },
  {
    id: 'btn_glass',
    name: 'Glass Neon',
    nameUz: 'Shaffof Shisha',
    category: 'buttonStyle',
    price: 800,
    description: "Yarim-shaffof kristall shisha effekti va nozik neon hoshiyalar.",
    icon: '💎',
    previewGradient: 'from-cyan-900 to-sky-950',
    tag: 'Shaffof',
    buttonStyles: {
      baseClass: 'bg-cyan-950/50 hover:bg-cyan-900/60 backdrop-blur-md border-2 border-cyan-500/50 text-cyan-100 shadow-md shadow-cyan-950/40 active:scale-95',
      selectedClass: 'bg-cyan-400 text-slate-950 border-cyan-300 font-black shadow-xl shadow-cyan-400/40',
      correctClass: 'bg-emerald-400 text-slate-950 border-emerald-300 font-black shadow-xl shadow-emerald-400/40',
      wrongClass: 'bg-rose-500 text-white border-rose-300 font-black shadow-xl shadow-rose-500/40',
      indicatorClass: 'bg-cyan-900/80 text-cyan-200',
    },
  },
  {
    id: 'btn_cyber',
    name: 'Cyber Deck',
    nameUz: 'Kiber Plita',
    category: 'buttonStyle',
    price: 1300,
    description: "Kiberpunk burchakli metall plitalar va yorqin fuchsia nuri.",
    icon: '⚡',
    previewGradient: 'from-fuchsia-900 to-purple-950',
    tag: 'Kiber',
    buttonStyles: {
      baseClass: 'bg-fuchsia-950/70 hover:bg-fuchsia-900/80 border-2 border-fuchsia-500/70 text-fuchsia-100 shadow-lg shadow-fuchsia-950/50 active:scale-95',
      selectedClass: 'bg-fuchsia-500 text-white border-fuchsia-300 font-black shadow-xl shadow-fuchsia-500/50',
      correctClass: 'bg-emerald-500 text-slate-950 border-emerald-300 font-black shadow-xl shadow-emerald-500/50',
      wrongClass: 'bg-rose-600 text-white border-rose-300 font-black shadow-xl shadow-rose-600/50',
      indicatorClass: 'bg-fuchsia-900 text-fuchsia-300',
    },
  },
];

export const DEFAULT_SKINS_CONFIG: PlayerSkinsConfig = {
  unlockedSkinIds: ['theme_cyber', 'avatar_bot', 'frame_classic', 'btn_modern'],
  equippedTheme: 'theme_cyber',
  equippedAvatar: 'avatar_bot',
  equippedCardFrame: 'frame_classic',
  equippedButtonStyle: 'btn_modern',
};

export function getSkinById(id: string): SkinItem | undefined {
  return ALL_SKINS.find((s) => s.id === id);
}

export function getEquippedSkins(config: PlayerSkinsConfig) {
  const theme = getSkinById(config.equippedTheme) || getSkinById('theme_cyber')!;
  const avatar = getSkinById(config.equippedAvatar) || getSkinById('avatar_bot')!;
  const cardFrame = getSkinById(config.equippedCardFrame) || getSkinById('frame_classic')!;
  const buttonStyle = getSkinById(config.equippedButtonStyle) || getSkinById('btn_modern')!;

  return {
    theme,
    avatar,
    cardFrame,
    buttonStyle,
  };
}
